apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:12
                  imagePullPolicy: "IfNotPresent"
                  ports:
                    - containerPort: 5432
                  envFrom:
                    - configMapRef:
                        name: postgres-config
                  volumeMounts:
                    - name: postgredb
                      mountPath: /var/lib/postgresql/data
                  env:
                    - name: POSTGRES_USER
                      valueFrom:
                        secretKeyRef:
                          name: postgres-env-secret
                          key: POSTGRES_USER
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: postgres-env-secret
                          key: POSTGRES_PASSWORD
            restartPolicy: Always
            volumes:
                - name: postgredb
                  persistentVolumeClaim:
                    claimName: postgres-persistent-volume-claim
