apiVersion: v1
data:
  redis-config:
    maxmemory 2mb
    maxmemory-policy allkeys-lru
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
  selfLink: /api/v1/namespace/default/configmaps/redis